name: Auto Merge Word of the Day PRs

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Verify Token Permissions
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/user)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Error: Personal Access Token (PAT) has insufficient permissions or is invalid."
            exit 1
          else
            echo "PAT is valid and has the necessary permissions."
          fi
        shell: bash

      - name: Merge PRs
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          scripts/merge_word_of_the_day.sh
