name: Delete merged add branches

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  cleanup:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'add')
    runs-on: ubuntu-24.04
    steps:
      - name: Delete branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = context.payload.pull_request.head.ref;
            const headRepo = context.payload.pull_request.head.repo.full_name;
            if (headRepo !== context.repo.owner + '/' + context.repo.repo) {
              core.notice(`Skipping branch deletion because ${branch} is from a fork`);
              return;
            }
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${branch}`,
            });
            core.info(`Deleted branch ${branch}`);
