name: Delete old branches

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-24.04
    steps:
      - name: Remove branches older than 3 days
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const skip = ['main', 'dev', 'holding'];
            const cutoff = Date.now() - 3 * 24 * 60 * 60 * 1000;
            const branches = await github.paginate(github.rest.repos.listBranches, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
            });
            for (const branch of branches) {
              if (skip.includes(branch.name)) continue;
              const commit = await github.rest.repos.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: branch.commit.sha,
              });
              const dateStr = commit.data.commit.committer?.date ?? commit.data.commit.author?.date;
              const commitDate = new Date(dateStr);
              if (commitDate.getTime() < cutoff) {
                try {
                  await github.rest.git.deleteRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: `heads/${branch.name}`,
                  });
                  core.info(`Deleted branch ${branch.name}`);
                } catch (error) {
                  core.warning(`Failed to delete ${branch.name}: ${error.message}`);
                }
              }
            }

