name: Promote holding to dev and main

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  promote:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Merge holding into dev and sync to main
        run: |
          set -e
          git fetch origin holding dev main
          git checkout dev
          git merge origin/holding --no-ff -m "Merge holding into dev"
          git push origin dev

          git checkout main
          git merge origin/dev --no-ff -m "Sync dev into main"
          git push origin main
