# .github/workflows/salvage_stale_data.yml
name: Salvage stale branches data

on:
  workflow_dispatch:      # Lancer manuellement ce workflow

permissions:
  contents: write
  pull-requests: write

jobs:
  salvage:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
      # On récupère toutes les branches distantes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all remote branches
        run: git fetch --all

      - name: Copy data from stale branches
        id: copydata
        env:
          HOLDING_BRANCH: 'holding'
        run: |
          # On repart proprement de la branche holding
          git checkout -B salvage-original origin/${HOLDING_BRANCH}
      
          # Liste des branches add-* excluant main/dev/holding
          stale_branches=$(git for-each-ref --format='%(refname:strip=3)' refs/remotes/origin/add-* | \
            grep -vE '^(main|dev|holding)$' || true)
      
          # On extrait successivement le dossier data/ de chaque branche
          for branch in $stale_branches; do
            echo "Traitement de la branche $branch"
            # Si un dossier data existe, on le récupère (sinon git checkout échoue et on continue)
            git checkout origin/$branch -- data/ || true
          done
      
          # On liste tous les fichiers qui diffèrent par rapport à la branche holding
          changed_files=$(git diff --name-only salvage-original -- data/ || true)
          new_count=$(echo "$changed_files" | grep -c '.json' || true)
      
          echo "Fichiers JSON ajoutés ou modifiés :"
          echo "$changed_files"
      
          # On exporte le nombre de fichiers JSON affectés pour les étapes suivantes
          echo "files_copied=$new_count" >> $GITHUB_OUTPUT

      - name: Commit changes from stale branches
        if: steps.copydata.outputs.files_copied != '0'
        run: |
          git add data/
          git commit -m "Add data from stale branches" || echo "No changes to commit"

      - name: Create Pull Request
        if: steps.copydata.outputs.files_copied != '0'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: "Salvage data from stale branches"
          branch: salvage-stale-${{ github.run_id }}
          title: "Salvage data from stale branches"
          body: "Copie les fichiers JSON des branches add-* obsolètes dans la branche holding."
          base: holding
